USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/lge/p970/BoardConfigVendor.mk

#BOARD_USE_USB_MASS_STORAGE_SWITCH := true

#TARGET_NO_BOOTLOADER := true
#TARGET_BOARD_PLATFORM := omap3
TARGET_BOARD_PLATFORM := unknown
TARGET_BOOTLOADER_BOARD_NAME := p970
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
#TARGET_ARCH_VARIANT := armv7-a-neon
#TARGET_GLOBAL_CFLAGS += -mtune=cortex-a8
#TARGET_GLOBAL_CPPFLAGS += -mtune=cortex-a8

BOARD_KERNEL_CMDLINE := 
BOARD_KERNEL_BASE := 0x80000000
BOARD_PAGE_SIZE := 0x00000800

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00600000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00600000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x28500000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x46DE0000
BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_PREBUILT_KERNEL := device/lge/p970/kernel

BOARD_HAS_NO_SELECT_BUTTON := true
TARGET_RECOVERY_PRE_COMMAND := "/system/bin/setup-recovery"
#BOARD_HAS_NO_MISC_PARTITION := true
#BOARD_USES_GENERIC_AUDIO := true
